### ISSUE TITLE
Not compiling with Support Library V7

### ISSUE THREAD

**Issue by alexrainman** [kevinskrei/XamarinPasscode#1]
Done building project "/Users/alexrainman/Downloads/Development/Xamarin/Libraries/XamarinPasscode-master/XamarinPasscode/Passcode.Google/Passcode.Google.csproj".-- FAILED

Build FAILED.
Errors:

/Users/alexrainman/Downloads/Development/Xamarin/Libraries/XamarinPasscode-master/XamarinPasscode/Passcode.Google/Passcode.Google.csproj (Build) ->
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets (_UpdateAndroidResgen target) ->

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Tool exited with code: 139. Output: /Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-mdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
```

/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-mdpi/abc_ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xxhdpi/abc_ic_clear_disabled.png: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ic_clear_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xxhdpi/abc_ic_clear_normal.png: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-mdpi/abc_ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xxhdpi/abc_ic_go.png: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-mdpi/abc_ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xxhdpi/abc_ic_search.png: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-mdpi/abc_ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-hdpi/abc_ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xhdpi/abc_ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/alexrainman/.local/share/Xamarin/Android.Support.v7.AppCompat/20.0.0/content/support/v7/appcompat/res/drawable-xxhdpi/abc_ic_voice_search.png: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG

```
 0 Warning(s)
 1 Error(s)
```

Time Elapsed 00:00:00.8233300

---------------------- Done ----------------------

Build: 1 error, 0 warnings

**Comment by kevinskrei** [comment]
Thank you for your pull request.
